CREATE DATABASE IF NOT EXISTS backend_cine;
USE backend_cine;

CREATE TABLE IF NOT EXISTS salas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  capacidad INT NOT NULL,
  tipo VARCHAR(50) NOT NULL COMMENT '2D, 3D, IMAX, 4DX'
);

CREATE TABLE IF NOT EXISTS peliculas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  genero VARCHAR(80) NOT NULL,
  duracion_min INT NOT NULL,
  clasificacion VARCHAR(10) NOT NULL COMMENT 'G, PG, PG-13, R'
);

CREATE TABLE IF NOT EXISTS horarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pelicula_id INT NOT NULL,
  sala_id INT NOT NULL,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  precio DECIMAL(8,2) NOT NULL,
  FOREIGN KEY (pelicula_id) REFERENCES peliculas(id) ON DELETE CASCADE,
  FOREIGN KEY (sala_id) REFERENCES salas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  telefono VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS boletos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  horario_id INT NOT NULL,
  cliente_id INT NOT NULL,
  asiento VARCHAR(10) NOT NULL,
  fecha_compra DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (horario_id) REFERENCES horarios(id) ON DELETE CASCADE,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);
